blueprint:
  name: Announce a phone call in a media player
  description: >
    Announces when there's a phone call, you're home and the ringer is low or muted.
  domain: automation
  input:
    phone_state:
      name: Phone State sensor
      description: Select the phone state sensor.
      selector:
        entity:
          integration: mobile_app
          domain: sensor
    phone_ringer_mode:
      name: Phone ringer mode sensor
      description: Select the phone ringer mode sensor.
      selector:
        entity:
          integration: mobile_app
          domain: sensor
    phone_ringer_volume:
      name: Phone ringer volume sensor
      description: Select the phone ringer volume sensor.
      selector:
        entity:
          integration: mobile_app
          domain: sensor          
    phone_interactive:
      name: Phone interactive sensor
      description: Select the phone interactive sensor.
      selector:
        entity:
          integration: mobile_app
          domain: sensor
    person:
      name: Person
      description: The person that needs to be in the required zone.
      selector:
        entity:
          domain: person
    zone:
      name: Zone
      description: The Zone that the person needs to be in.
      default: zone.home
      selector:
          entity:
            domain: zone
    media_player: 
      name: Media Player
      description: The media player to announce with.
      selector:
        entity:
          domain: media_player
    message: 
      name: Message
      description: The message to announce.
    delay_time:
      name: Delay
      description: How much time to give you a chance to answer before announcing.
      default: for: "00:00:07"

trigger:
  - platform: state
    entity_id: !input phone_state
    to: "ringing"
    for: !delay_time
variables: 
  zone: !input zone
  zone_name: "{{ zone[5:] }}"
  entity: !input person
condition:
  - "{{is_state(entity, zone_name)}}"
  - condition: numeric_state
    entity_id: !input phone_ringer_volume
    below: 5
  - condition: state
    entity_id: !phone_interactive
    state: off
action:
  - service: tts.microsoft_say
    data:
      entity_id: !input media_player
      message: !input message
